name: Python application CI

on:
  push:
    branches: [main] # 只有在 main 分支推送时触发
  pull_request:
    branches: [main] # 只有在 main 分支的拉取请求时触发

jobs:
  build:
    runs-on: ubuntu-latest # 使用最新版的 Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11 # 指定 Python 版本，例如 3.8、3.9 等

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        pytest 

    #- name: Deploy
    #  run: |
    #    # 在这里可以添加部署步骤，如部署到服务器或者云服务商等
    
    
    
